// Generated by generate-types.ts
// Generated at 2024-11-20T20:21:38.017Z
// Source: https://jsonplaceholder.typicode.com/posts/1/comments

export interface Comment {
    body?:   string;
    email?:  string;
    id?:     number;
    name?:   string;
    postId?: number;
}

