// Generated by generate-types.ts
// Generated at 2024-11-20T20:21:38.058Z
// Source: https://jsonplaceholder.typicode.com/posts

export interface Post {
    body?:   string;
    id?:     number;
    title?:  string;
    userId?: number;
}

