// Generated by rest-to-ts
// Generated at 2024-11-25T18:35:23.626Z
// Sources:
// - http://localhost:3000/posts/1/comments

export type Comment = {
    authorId:    number;
    id:          number;
    isFeatured?: boolean;
    postId:      number;
    title:       string;
}

