// Generated by rest-to-ts
// Generated at 2024-11-21T18:50:46.570Z
// Sources:
// - http://localhost:3000/posts/1/comments

export interface Comment {
    id:     number;
    postId: number;
    title:  string;
}

