// Generated by rest-to-ts
// Generated at 2024-11-25T06:00:04.281Z
// Sources:
// - http://localhost:3000/mirror/123
// - http://localhost:3000/mirror/456?query=test
// - http://localhost:3000/mirror/789?query=test&page=1&limit=10

export type Mirror = {
    id:           string;
    queryParams?: QueryParams;
}

export type QueryParams = {
    limit?: string;
    page?:  string;
    query:  string;
}

