// Generated by rest-to-ts
// Generated at 2024-11-25T20:42:22.854Z
// Sources:
// - http://localhost:3000/posts/1
// - http://localhost:3000/posts/3
// - http://localhost:3000/posts/5
// - http://localhost:3000/posts/2

export type Post = {
    authorId:     number;
    description?: string;
    id:           number;
    tag?:         string;
    title:        string;
}

