// Generated by rest-to-ts
// Generated at 2024-11-25T18:35:23.618Z
// Sources:
// - http://localhost:3000/user

export type User = {
    email:     string;
    firstName: string;
    id:        number;
    image?:    string;
    lastName:  string;
}

